name: Release

on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
          with:
            node-version: 16
            registry-url: https://registry.npmjs.org/
      - run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN}}

